### ISSUE TITLE
Respect LR order when not "Custom"

### ISSUE THREAD

**Issue by matzeeable** [matzeeable/wplr-rml#5]
See #2 , @winstonyin:

> However, the claimed "respects LR order" doesn't actually work when images are ordered by capture time in Lightroom. Is it possible to make the default ordering for WP/LR collections in RML filename_asc? (I understand this is a completely separate issue.)
> As far as I understand, capture time ordering is the default in LR, so the "sort" column in DB is 0 for images in this kind of collection. The sync process from WP/LR plugin loops over images in a random order.
> Currently, I have to manually trigger republish in LR two times to cause the correct order in RML folders for capture time ordered collections. This is very inconvenient. Note that in the past, WP/LR collections created by their extension allowed sorting within RML.

Perhaps we have to discuss this with Jordy. @jordymeow, is there any chance to get the `sort` column filled even when the order is not `Custom`?

**Comment by jordymeow** [comment]
Hi @matzeeable. I never got the ping for that mention but I found this by chance :)

With the latest version of WP/LR Sync (5+), you can get the order of a certain collection by doing this:

`global $wplr;
$wpdb->get_meta( 'collection_order', $wp_col_id );`

Currently, that will return name-asc, date-asc or date-desc. Based on that, you can re-order the results if you like.

**Comment by matzeeable** [comment]
Hi @jordymeow,

thanks for that info. Currently this is handled by the `wplr_relations` column `sort`:

https://github.com/matzeeable/wplr-rml/blob/ade13e4d1a0dac492c7de0ccbc1f6eba1a1f5ef7/inc/sync/Attachments.class.php#L48-L62

So, since v5 of your plugin every attachment has a metadata with the given `sort`? Do you have any idea how to implement that in the SQL? I had not yet a look at the new sort mechanism. :-)

**Comment by jordymeow** [comment]
Actually, your code should be fine :) WP/LR Sync still uses `sort`. The thing is that, in Lightroom, there was no way to order by something else that the Custom Order. Ordering by date, for example, was not being replicated through the Lightroom API and therefore, I had to add some way to choose an order for every single collection. I am keeping that information in the `collection_order` meta, but it also updates the `sort` column.
